# Generated by Django 4.1.4 on 2023-01-14 19:33

from django.db import migrations, models
import django.db.models.deletion
import object.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Jméno:')),
                ('object', models.CharField(max_length=100, unique=True, verbose_name='Název objektu:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis objektu:')),
                ('photo', models.FileField(blank=True, null=True, upload_to=object.models.object_path, verbose_name='Fotka:')),
                ('scene_bin', models.FileField(null=True, upload_to=object.models.model_path, verbose_name='BIN soubor:')),
                ('scene_gltf', models.FileField(null=True, upload_to=object.models.model_path, verbose_name='GLTF soubor:')),
            ],
            options={
                'verbose_name_plural': 'Objects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Textures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textures', models.ImageField(null=True, upload_to=object.models.texture_path)),
                ('object_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='object.object')),
            ],
        ),
    ]
