# Generated by Django 4.1.4 on 2022-12-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_alter_object_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Popis objektu:'),
        ),
    ]
