# Generated by Django 4.1.4 on 2022-12-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0007_object_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='directory',
        ),
    ]
