# Generated by Django 4.1.4 on 2022-12-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0009_alter_object_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['name'], 'verbose_name_plural': 'Objects'},
        ),
    ]
