# Generated by Django 4.1.4 on 2023-01-04 20:49

from django.db import migrations, models
import object.models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0012_alter_object_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='zip_file',
            field=models.FileField(null=True, upload_to=object.models.zip_path, verbose_name='Zip soubor:'),
        ),
    ]
