# Generated by Django 4.1.4 on 2023-01-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0013_alter_object_zip_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='zip_file',
        ),
    ]
