# Generated by Django 4.1.4 on 2023-01-14 18:00

from django.db import migrations, models
import django.db.models.deletion
import object.models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0014_remove_object_zip_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textures', models.ImageField(blank=True, null=True, upload_to=object.models.texture_path)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='textures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='object.textures'),
        ),
    ]
