# Generated by Django 4.1.4 on 2023-01-14 18:06

from django.db import migrations, models
import object.models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0016_alter_object_textures'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='scene_bin',
            field=models.FileField(null=True, upload_to=object.models.model_path, verbose_name='BIN soubor:'),
        ),
        migrations.AddField(
            model_name='object',
            name='scene_gltf',
            field=models.FileField(null=True, upload_to=object.models.model_path, verbose_name='GLTF soubor:'),
        ),
        migrations.AlterField(
            model_name='object',
            name='object',
            field=models.CharField(max_length=100, unique=True, verbose_name='Název objektu:'),
        ),
    ]
