# Generated by Django 4.1.4 on 2023-01-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0017_object_scene_bin_object_scene_gltf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textures',
            name='textures',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
