# Generated by Django 4.1.4 on 2023-01-14 18:47

from django.db import migrations, models
import object.models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0018_alter_textures_textures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textures',
            name='textures',
            field=models.ImageField(blank=True, null=True, upload_to=object.models.object_path),
        ),
    ]
