# Generated by Django 4.1.4 on 2023-01-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0019_alter_textures_textures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textures',
            name='textures',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
