# Generated by Django 4.1.4 on 2023-01-14 19:10

from django.db import migrations, models
import django.db.models.deletion
import object.models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0020_alter_textures_textures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='textures',
        ),
        migrations.AddField(
            model_name='textures',
            name='object_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='object.object'),
        ),
        migrations.AlterField(
            model_name='textures',
            name='textures',
            field=models.ImageField(null=True, upload_to=object.models.texture_path),
        ),
    ]
