# Generated by Django 4.1.4 on 2023-01-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0021_remove_object_textures_textures_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textures',
            name='textures',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
