# Generated by Django 4.1.4 on 2023-01-14 19:13

from django.db import migrations, models
import object.models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0022_alter_textures_textures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textures',
            name='textures',
            field=models.ImageField(null=True, upload_to=object.models.texture_path),
        ),
    ]
