# Generated by Django 4.1.4 on 2022-12-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.FileField(null=True, upload_to='', verbose_name='Popis objektu:'),
        ),
    ]
