# Generated by Django 4.1.4 on 2022-12-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0005_alter_object_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis objektu:'),
        ),
    ]
