# Generated by Django 4.1.4 on 2022-12-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0006_alter_object_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='directory',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
