# Generated by Django 4.1.4 on 2022-12-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jmeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Jméno:')),
            ],
            options={
                'verbose_name_plural': 'Jmeno',
                'ordering': ['name'],
            },
        ),
    ]
